# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.patrick-leonard.com
title: Patrick Leonard
email: me@patrick-leonard.com
author: Patrick Leonard
description: > # "Patrick Leonard. Building with JavaScript, Leaflet, D3, C3"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
name: Patrick Leonard
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pjleonard37
  - title: linkedin
    url: https://www.linkedin.com/in/leonardpatrick
  - title: twitter
    url: https://mobile.twitter.com/PJ_Leonard
  - title: e-mail
    url: mailto:me@patrick-leonard.com
